apiVersion: v1
entries:
  ravendb-operator:
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2026-05-26T04:48:14.0237966+02:00"
    description: RavenDB Kubernetes Operator
    digest: 9ea6f82a5235d758947321d90725ce43a187910146eee5c99391ed8c46532aeb
    icon: https://raw.githubusercontent.com/ravendb/ravendb-operator/refs/heads/main/assets/logo.png
    maintainers:
    - name: ravendb
      url: https://ravendb.net
    name: ravendb-operator
    type: application
    urls:
    - https://ravendb.github.io/ravendb-operator/helm/ravendb-operator-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-05-26T04:48:14.022116+02:00"
    description: RavenDB Kubernetes Operator
    digest: 3a12259c659bc5db7514fcfea7abb821a6a8faf9747c73ca4be7d04732fce58d
    icon: https://s3.us-west-2.amazonaws.com/static.ravendb.net/ravendb-mp-black.png
    maintainers:
    - name: ravendb
      url: https://ravendb.net
    name: ravendb-operator
    type: application
    urls:
    - https://ravendb.github.io/ravendb-operator/helm/ravendb-operator-1.0.0.tgz
    version: 1.0.0
generated: "2026-05-26T04:48:14.0193094+02:00"
