{{- if .Values.secrets.caCert.file }}
{{- if ne .Values.spec.mode "None" }}
{{- fail "secrets.caCert.file can only be used when spec.mode=None" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.caCert.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ravendb-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.secrets.caCert.file | b64enc }}
{{- end }}
