{{- if .Values.secrets.clientCert.file }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.clientCert.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ravendb-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  client.pfx: {{ .Values.secrets.clientCert.file | b64enc }}
{{- end }}
