{{- if .Values.secrets.clusterCert.file }}
{{- if ne .Values.spec.mode "None" }}
{{- fail "secrets.clusterCert.file can only be used when spec.mode=None" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.clusterCert.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ravendb-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  server.pfx: {{ .Values.secrets.clusterCert.file | b64enc }}
{{- end }}
