{{- if .Values.secrets.license.file }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.license.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ravendb-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  license.json: {{ .Values.secrets.license.file | b64enc }}
{{- end }}
